apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\vmari\bin\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "4000"
    port: 4000
    targetPort: 4000
  selector:
    io.kompose.service: wordpress
status:
  loadBalancer: {}
