version: '2'
services:
  nginxBackend:
    image: 'nginx:latest'
    container_name: 'back-end'
    expose:
      - '80'
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
      - ./backendError.log:/etc/nginx/error_log.log
  nginx:
    image: 'nginx:latest'
    container_name: 'Proxy-server'
    ports:
      - '3000:80'
      - '4000:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - './nginxError.log:/etc/nginx/error_log.log'
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
networks:
  frontend:
    driver: bridge
    ipam: 
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1 