apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\vmari\bin\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: {{ .Release.Name }}mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\vmari\bin\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: yes
        - name: MARIADB_DATABASE
          value: bitnami_wordpress
        - name: MARIADB_USER
          value: bn_wordpress
        image: docker.io/bitnami/mariadb:10.3-debian-10
        imagePullPolicy: ""
        name: mariadb
        resources: {}
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: charts-mariadb-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: charts-mariadb-data
        persistentVolumeClaim:
          claimName: charts-mariadb-data
status: {}
