apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\vmari\bin\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: {{ .Release.Name }}nginx
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 80
  - name: "4000"
    port: 4000
    targetPort: 443
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
