apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\vmari\bin\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wordpress
  name: {{ .Release.Name }}wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\vmari\bin\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: wordpress
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: yes
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: WORDPRESS_DATABASE_NAME
          value: bitnami_wordpress
        - name: WORDPRESS_DATABASE_USER
          value: bn_wordpress
        image: docker.io/bitnami/wordpress:5-debian-10
        imagePullPolicy: ""
        name: wordpress
        ports:
        - containerPort: 8080
        - containerPort: 4000
        resources: {}
        volumeMounts:
        - mountPath: /bitnami/wordpress
          name: charts-wordpress-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: charts-wordpress-data
        persistentVolumeClaim:
          claimName: charts-wordpress-data
status: {}
